name       : sc-controller
version    : 0.3.15
release    : 22
source     :
    - https://github.com/kozec/sc-controller/archive/v0.3.15.tar.gz : e31dc060b9b2c5a1176954f165cbf09be5e625a75d2bd8224e5b522184ca5cdb
license    : GPL-2.0
component  : games
summary    : User-mode driver and GTK3 based GUI for Steam Controller
description: |
    User-mode driver and GTK3 based GUI for Steam Controller.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - python-setuptools
rundeps    :
    - linux-headers
    - python-pylibacl
build      : |
    %python_setup
install    : |
    %python_install
