name       : sc-controller
version    : 0.2.17
release    : 3
source     :
    - https://github.com/kozec/sc-controller/archive/v0.2.17.tar.gz : 2e7efa72e9c480ed2dd64afd89d6d7cd31593b677bf52823b55b98a0c542cbf1
license    : GPL-2.0
component  : games
summary    : User-mode driver and GTK3 based GUI for Steam Controller
description: |
    User-mode driver and GTK3 based GUI for Steam Controller.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
