name       : sc-controller
version    : 0.3.11
release    : 19
source     :
    - https://github.com/kozec/sc-controller/archive/v0.3.11.tar.gz : fe305b9cad196d7d9d02ccca072af20e1d11fa13393f86e88c47f509c00fc30e
license    : GPL-2.0
component  : games
summary    : User-mode driver and GTK3 based GUI for Steam Controller
description: |
    User-mode driver and GTK3 based GUI for Steam Controller.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - python-setuptools
rundeps    :
    - linux-headers
    - python-pylibacl
build      : |
    %python_setup
install    : |
    %python_install
