name       : sc-controller
version    : 0.3.16
release    : 23
source     :
    - https://github.com/kozec/sc-controller/archive/v0.3.16.tar.gz : a38661b1b1e458495395a84cef87f060d9bd1d9df5c0f66d6aa672f85bfcd0ce
license    : GPL-2.0
component  : games
summary    : User-mode driver and GTK3 based GUI for Steam Controller
description: |
    User-mode driver and GTK3 based GUI for Steam Controller.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - python-setuptools
rundeps    :
    - linux-headers
    - python-pylibacl
build      : |
    %python_setup
install    : |
    %python_install
