name       : sc-controller
version    : 0.4.8
release    : 32
source     :
    - https://github.com/kozec/sc-controller/archive/refs/tags/v0.4.8.tar.gz : 2abd6261e86ea396e306d29b9eb218ed1b34c2bc868ebd81a25561f025c6754a
homepage   : https://github.com/kozec/sc-controller
license    : GPL-2.0-only
component  : games
summary    : User-mode driver, mapper and GTK3 based GUI for Steam Controller, DS4 and similar controllers
description: |
    User-mode driver, mapper and GTK3 based GUI for Steam Controller, DS4 and similar controllers.
builddeps  :
    - pkgconfig(libcrypt)
    - pkgconfig(pygobject-3.0)
    - python-setuptools
    - python-pylibacl
rundeps    :
    - linux-headers
    - python-evdev
    - python-pylibacl
build      : |
    %python_setup
install    : |
    %python_install
