name       : sc-controller
version    : 0.3.0.3
release    : 4
source     :
    - https://github.com/kozec/sc-controller/archive/v0.3.0.3.tar.gz : 60ba883080a0e2979b9e4a79555294dd4954dc7889544d62c734433e1cd59c20
license    : GPL-2.0
component  : games
summary    : User-mode driver and GTK3 based GUI for Steam Controller
description: |
    User-mode driver and GTK3 based GUI for Steam Controller.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
