name       : sc-controller
version    : 0.4.0.1
release    : 24
source     :
    - https://github.com/kozec/sc-controller/archive/v0.4.0.1.tar.gz : a83e42899e75040dbbe5b22f6e2c555e68aa41e549b807565f4bcec1dc94190e
license    : GPL-2.0
component  : games
summary    : User-mode driver and GTK3 based GUI for Steam Controller
description: |
    User-mode driver and GTK3 based GUI for Steam Controller.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - python-setuptools
rundeps    :
    - linux-headers
    - python-evdev
    - python-pylibacl
build      : |
    %python_setup
install    : |
    %python_install
