name       : sc-controller
version    : 0.4.3
release    : 28
source     :
    - https://github.com/kozec/sc-controller/archive/v0.4.3.tar.gz : 808cfeb7fc827a2b69d1f488bd5463903ed99cb045add34c7b79779e00827465
license    : GPL-2.0
component  : games
summary    : User-mode driver and GTK3 based GUI for Steam Controller
description: |
    User-mode driver and GTK3 based GUI for Steam Controller.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - python-setuptools
rundeps    :
    - linux-headers
    - python-evdev
    - python-pylibacl
build      : |
    %python_setup
install    : |
    %python_install
