name       : sc-controller
version    : 0.4.7
release    : 31
source     :
    - https://github.com/kozec/sc-controller/archive/v0.4.7.tar.gz : b564d2f35a0a41ed5ea17df4add545a6e2035b6444227880131cdcced620ef04
license    : GPL-2.0-only
component  : games
summary    : User-mode driver, mapper and GTK3 based GUI for Steam Controller, DS4 and similar controllers
description: |
    User-mode driver, mapper and GTK3 based GUI for Steam Controller, DS4 and similar controllers.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - python-setuptools
    - python-pylibacl
rundeps    :
    - linux-headers
    - python-evdev
    - python-pylibacl
build      : |
    %python_setup
install    : |
    %python_install
