name       : sc-controller
version    : 0.4.6.1
release    : 30
source     :
    - https://github.com/kozec/sc-controller/archive/v0.4.6.1.tar.gz : 550572c6dd38e9b905015d88ad81f4e3d7d8a18cda50c06ec245a3cccc6df295
license    : GPL-2.0-only
component  : games
summary    : User-mode driver, mapper and GTK3 based GUI for Steam Controller, DS4 and similar controllers
description: |
    User-mode driver, mapper and GTK3 based GUI for Steam Controller, DS4 and similar controllers.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - python-setuptools
    - python-pylibacl
rundeps    :
    - linux-headers
    - python-evdev
    - python-pylibacl
strip      : no
build      : |
    %python_setup
install    : |
    %python_install
