name       : sc-controller
version    : 0.3.1
release    : 5
source     :
    - https://github.com/kozec/sc-controller/archive/v0.3.1.tar.gz : a090ca37554882e704b429139117c82030a27a17b1a70b4d11297624c81c4a14
license    : GPL-2.0
component  : games
summary    : User-mode driver and GTK3 based GUI for Steam Controller
description: |
    User-mode driver and GTK3 based GUI for Steam Controller.
builddeps  :
    - pkgconfig(pygobject-3.0)
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
